# Generated by Django 4.2.20 on 2025-04-08 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='processamento',
            table='processamento',
        ),
    ]
