# Generated by Django 4.2.20 on 2025-04-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_processamento_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamento',
            name='average',
            field=models.FloatField(db_column='media', default=0),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='median',
            field=models.FloatField(db_column='mediana', default=0),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='status',
            field=models.CharField(choices=['PROCESSANDO', 'FINALIZADO'], default='PROCESSANDO'),
        ),
    ]
